# Pull base image.
FROM jlesage/baseimage-gui:ubuntu-22.04-v4

# Define working directory.
WORKDIR /tmp

# Generate and install favicons.
RUN \
	APP_ICON_URL=https://raw.githubusercontent.com/angelics/unraid-docker-tartube/main/tartube_icon.png && \
	install_app_icon.sh "$APP_ICON_URL"
 
# Define download URLs.
ARG TARTUBE_VERSION=2.4.429
ARG TARTUBE_URL=https://github.com/axcore/tartube/releases/download/v${TARTUBE_VERSION}/python3-tartube_${TARTUBE_VERSION}.deb
# ARG TARTUBE_URL=["curl -s https://api.github.com/repos/axcore/tartube/releases/latest \
# 		| grep -v STRICT | grep "browser_download_url.*deb" \
# 		| cut -d : -f 2,3 \
# 		| tr -d \""]

# install packages
ARG     DEBIAN_FRONTEND=noninteractive
# RUN     sudo apt-get update -y
# RUN	sudo apt-get upgrade -y
RUN \
	add-pkg \
		ffmpeg \
		python3-full \
		python3-matplotlib \
		python3-pip \
		python3-feedparser \
		python3-requests \
    		python3-cairo \
    		python3-cairocffi \
    		gobject-introspection \
		python3-gi \
    		python-gi-dev \
		gir1.2-gtk-3.0 \
    		libgtk-3-0 \
    		libgtk-3-common \
    		aria2 \
		dbus-x11 \
		at-spi2-core \	
		locales \
    		atomicparsley \
  && sed-patch 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen \
  && locale-gen

RUN \
  python3 -m pip install --no-cache-dir --upgrade pip \
  && python3 -m pip install --no-cache-dir \
    streamlink \
# playsound
    yt-dlp \
    moviepy \

### Install Tartube
		&& \
	add-pkg --virtual build-dependencies \
		wget \
		&& \
	wget -q ${TARTUBE_URL} && \
	dpkg -i python3-tartube_${TARTUBE_VERSION}.deb && \
	del-pkg build-dependencies && \
	rm -rf /tmp/* /tmp/.[!.]*

RUN adduser --disabled-password --gecos ""  tartube && \
    touch /usr/local/bin/docker-entrypoint.sh && \
    echo '#!/bin/sh' >> /usr/local/bin/docker-entrypoint.sh && \
    echo 'set -e' >> /usr/local/bin/docker-entrypoint.sh && \
    echo 'PUID=${PUID:-20000}' >> /usr/local/bin/docker-entrypoint.sh && \
    echo 'PGID=${PGID:-20000}' >> /usr/local/bin/docker-entrypoint.sh && \
    echo 'groupmod -o -g "$PGID" tartube' >> /usr/local/bin/docker-entrypoint.sh && \
    echo 'usermod -o -u "$PUID" tartube' >> /usr/local/bin/docker-entrypoint.sh && \
    echo 'chown mediaelch:mediaelch /home/tartube' >> /usr/local/bin/docker-entrypoint.sh && \
    echo 'chown mediaelch:mediaelch /home/tartube/.*' >> /usr/local/bin/docker-entrypoint.sh && \
    echo 'exec "$@"' >> /usr/local/bin/docker-entrypoint.sh && \
    chmod +x /usr/local/bin/docker-entrypoint.sh && \
    echo 'export LC_ALL=en_US.UTF-8' >> /home/tartube/.profile && \
    echo 'export LANG=en_US.UTF-8' >> /home/tartube/.profile && \
    echo 'export LANGUAGE=en_US.UTF-8' >> /home/tartube/.profile && \
    echo 'export LC_ALL=en_US.UTF-8' >> /home/tartube/.bashrc && \
    echo 'export LANG=en_US.UTF-8' >> /home/tartube/.bashrc && \
    echo 'export LANGUAGE=en_US.UTF-8' >> /home/tartube/.bashrc && \
    touch /startapp.sh && \
    echo '#!/bin/sh' >> /startapp.sh && \
    echo 'exec env HOME=/config ~/.local/bin/tartube' >> /startapp.sh && \
    chmod +x /startapp.sh && \


# Set environment variables.
RUN \
    set-cont-env APP_NAME "Tartube" && \
    set-cont-env APP_VERSION "$TARTUBE_VERSION"
	
RUN     apt-get -y autoremove
RUN     apt-get -y clean
RUN     rm -rf /var/lib/sudo apt/lists/*


# Define variables.
ENV     LANGUAGE=en_US:en \
	LC_ALL=en_US.UTF-8 \
	APP_NAME="Tartube" \
	DISPLAY_WIDTH="1600" \
	DISPLAY_HEIGHT="900" \
	DARK_MODE=0 \
	SECURE_CONNECTION=0 \
	SECURE_CONNECTION_VNC_METHOD=SSL \
	SECURE_CONNECTION_CERTS_CHECK_INTERVAL=60 \
	WEB_LISTENING_PORT=5800 \
	VNC_LISTENING_PORT=5900 \
	VNC_PASSWORD= \
	ENABLE_CJK_FONT=0
VOLUME ["/storage/"]
VOLUME ["/config/"]
EXPOSE 5800
ENTRYPOINT ["tartube"]
# ENTRYPOINT ["~/.local/bin/tartube"]
