name: Docker Image Push tt

on:
  workflow_dispatch:
    branches: [ master ]
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        DOCKER_TOKEN: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_TOKEN 
    - name: Build Docker image
      run: docker build -t ozrygle/test:tt .
      
    - name: Docker Push latest
      run: docker push ozrygle/test:ttlatest
    - name: Docker Push tt-${{ github.event.repository.updated_at}}  
      run: docker push ozrygle/test:tt-${{ github.event.repository.updated_at}}
