name: Docker Image Push tt

on:
  workflow_dispatch:
    branches: [ master ]
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Send TIME -> env
      run: echo "NOW=TT_$(date +'%Y_%m_%d_%H_%M_%S')" >> $GITHUB_ENV
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        DOCKER_TOKEN: ${{secrets.DOCKER_PASSWORD}}
        TIME: ${{env.NOW}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_TOKEN 
    - name: Build Docker image tt-latest
      run: docker build -t ozrygle/test:tt-latest .
    - name: Docker Push tt-latest
      run: docker push ozrygle/test:tt-latest
    - name: Build Docker image test:$TIME
      run: docker build -t ozrygle/test:$TIME .
    - name: Docker Push $TIME
      run: docker push ozrygle/test:$TIME
